version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go_graphql_postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
